### ISSUE TITLE
inference FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint_gpt2-small_full_train_all_instruct_6_2_0.5_96/model_s2036.pth'

### ISSUE THREAD

**Issue by m6129** [liuxu77/UniTime#2]
Dear developer, where to get the file _checkpoint_gpt2-small_full_train_all_instruct_6_2_0.5_96/model_s2036.pth_ ?
It pops up as an error when trying to make a prediction via inference
```
Traceback (most recent call last):
  File "/kaggle/working/UniTime/run.py", line 69, in <module>
    engine.test()
  File "/kaggle/working/UniTime/engines/engine.py", line 180, in test
    self.model.load_state_dict(torch.load(path))
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint_gpt2-small_full_train_all_instruct_6_2_0.5_96/model_s2036.pth'
```
https://www.kaggle.com/mrantonzaitsev/unitime-inference

**Comment by m6129** [comment]
I took the model that is formed for the few-shot, I hope I understood your intent correctly
