### ISSUE TITLE
how resize seq_len?

### ISSUE THREAD

**Issue by m6129** [liuxu77/UniTime#5]
Hello, Dear Developer.
I tried changing the seq_len to 720, 336, but I've encountered [errors](https://www.kaggle.com/mrantonzaitsev/new-seq-len-unitime-finetuning)
```
Traceback (most recent call last):
  File "/kaggle/working/UniTime_for_Kaggle/run_univariate.py", line 67, in <module>
    engine.train()
  File "/kaggle/working/UniTime_for_Kaggle/engines/engine_univariate.py", line 133, in train
    loss = self.train_engines[idx].train_batch(batch, self.model, self.optimizer)
  File "/kaggle/working/UniTime_for_Kaggle/engines/engine_forecasting.py", line 45, in train_batch
    loss = self.criterion(outputs, batch_y)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 535, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 3328, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/opt/conda/lib/python3.10/site-packages/torch/functional.py", line 73, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (624) must match the size of tensor b (1440) at non-singleton dimension 1
CPU times: user 648 ms, sys: 134 ms, total: 782 ms
Wall time: 37.1 s
```
How to solve this problem properly, I want to test your model with a different seq_len?

**Comment by liuxu77** [comment]
Hi, I think you could print out the shapes of outputs and batch_y, to see if there is any inconsistency.
